name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'cohesive-keel-471913-b3'
  REGION: 'europe-west1'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Clear old Docker credentials
        run: rm -rf ~/.docker/config.json

      - name: Authenticate Docker with GCloud
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Frontend
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/paaros/trust-portal"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: Deploy Frontend to Cloud Run
        run: |-
          gcloud run deploy trust-portal \
            --image="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/paaros/trust-portal" \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated
